#############################################################################
# Makefile for building: bin/XeVe
# Generated by qmake (2.01a) (Qt 4.6.3) on: Wed Nov 13 11:23:09 2013
# Project:  XeVe.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile XeVe.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I-I/ikpv2/include -I-mcmodel=large -Imoc -Iui
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/ikpv2/lib -lmfile -lm -mcmodel=large -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/xeve_window.cpp \
		src/XiaEventReader.cpp \
		src/polynom.cpp \
		src/addback.cpp \
		src/advanced_strings.cpp \
		src/evaluate.cpp moc/moc_xeve_window.cpp \
		moc/moc_evaluate.cpp
OBJECTS       = obj/main.o \
		obj/xeve_window.o \
		obj/XiaEventReader.o \
		obj/polynom.o \
		obj/addback.o \
		obj/advanced_strings.o \
		obj/evaluate.o \
		obj/moc_xeve_window.o \
		obj/moc_evaluate.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		XeVe.pro
QMAKE_TARGET  = XeVe
DESTDIR       = bin/
TARGET        = bin/XeVe

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui/ui_xeve_window.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: XeVe.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile XeVe.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile XeVe.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/XeVe1.0.0 || $(MKDIR) obj/XeVe1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/XeVe1.0.0/ && $(COPY_FILE) --parents src/xeve_window.h src/XiaEventReader.h src/polynom.h src/event.h src/addback.h src/dgf_format.h src/advanced_strings.h src/evaluate.h obj/XeVe1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/xeve_window.cpp src/XiaEventReader.cpp src/polynom.cpp src/addback.cpp src/advanced_strings.cpp src/evaluate.cpp obj/XeVe1.0.0/ && $(COPY_FILE) --parents src/xeve_window.ui obj/XeVe1.0.0/ && (cd `dirname obj/XeVe1.0.0` && $(TAR) XeVe1.0.0.tar XeVe1.0.0 && $(COMPRESS) XeVe1.0.0.tar) && $(MOVE) `dirname obj/XeVe1.0.0`/XeVe1.0.0.tar.gz . && $(DEL_FILE) -r obj/XeVe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_xeve_window.cpp moc/moc_evaluate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_xeve_window.cpp moc/moc_evaluate.cpp
moc/moc_xeve_window.cpp: src/xeve_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/xeve_window.h -o moc/moc_xeve_window.cpp

moc/moc_evaluate.cpp: src/event.h \
		src/polynom.h \
		src/addback.h \
		src/evaluate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/evaluate.h -o moc/moc_evaluate.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_xeve_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_xeve_window.h
ui/ui_xeve_window.h: src/xeve_window.ui
	/usr/bin/uic-qt4 src/xeve_window.ui -o ui/ui_xeve_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp src/xeve_window.h \
		src/evaluate.h \
		src/event.h \
		src/polynom.h \
		src/addback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/xeve_window.o: src/xeve_window.cpp src/xeve_window.h \
		ui/ui_xeve_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/xeve_window.o src/xeve_window.cpp

obj/XiaEventReader.o: src/XiaEventReader.cpp src/dgf_format.h \
		src/event.h \
		src/XiaEventReader.h \
		src/advanced_strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/XiaEventReader.o src/XiaEventReader.cpp

obj/polynom.o: src/polynom.cpp src/polynom.h \
		src/advanced_strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/polynom.o src/polynom.cpp

obj/addback.o: src/addback.cpp src/addback.h \
		src/polynom.h \
		src/event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/addback.o src/addback.cpp

obj/advanced_strings.o: src/advanced_strings.cpp src/event.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/advanced_strings.o src/advanced_strings.cpp

obj/evaluate.o: src/evaluate.cpp src/XiaEventReader.h \
		src/event.h \
		src/dgf_format.h \
		src/polynom.h \
		src/addback.h \
		src/evaluate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/evaluate.o src/evaluate.cpp

obj/moc_xeve_window.o: moc/moc_xeve_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_xeve_window.o moc/moc_xeve_window.cpp

obj/moc_evaluate.o: moc/moc_evaluate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_evaluate.o moc/moc_evaluate.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

